// Auto-generated by LLM3dEngine binding generator
// Do not edit manually

#ifndef QUICKJS_BINDING_GEN_H
#define QUICKJS_BINDING_GEN_H

extern "C" {
#include "quickjs.h"
}

void quickjs_register_generated_bindings(JSContext *ctx, JSValue global);

#endif // QUICKJS_BINDING_GEN_H
