#!/usr/bin/env python3
"""
Binding generator for LLM3dEngine.
Reads Godot's extension_api.json and generates:
  1. QuickJS C++ binding code (quickjs_binding_gen.cpp/h)
  2. TypeScript declaration files (engine-core.d.ts)
"""

import json
import os
import sys
from pathlib import Path

# Type mapping: Godot type -> TypeScript type
GODOT_TO_TS = {
    "bool": "boolean",
    "int": "number",
    "float": "number",
    "String": "string",
    "StringName": "string",
    "NodePath": "string",
    "Vector2": "Vector2",
    "Vector2i": "Vector2i",
    "Vector3": "Vector3",
    "Vector3i": "Vector3i",
    "Vector4": "Vector4",
    "Quaternion": "Quaternion",
    "Transform2D": "Transform2D",
    "Transform3D": "Transform3D",
    "Basis": "Basis",
    "Color": "Color",
    "Rect2": "Rect2",
    "Rect2i": "Rect2i",
    "AABB": "AABB",
    "Plane": "Plane",
    "Projection": "Projection",
    "RID": "RID",
    "Callable": "Callable",
    "Signal": "Signal",
    "Array": "GodotArray",
    "Dictionary": "GodotDictionary",
    "PackedByteArray": "PackedByteArray",
    "PackedInt32Array": "PackedInt32Array",
    "PackedInt64Array": "PackedInt64Array",
    "PackedFloat32Array": "PackedFloat32Array",
    "PackedFloat64Array": "PackedFloat64Array",
    "PackedStringArray": "PackedStringArray",
    "PackedVector2Array": "PackedVector2Array",
    "PackedVector3Array": "PackedVector3Array",
    "PackedColorArray": "PackedColorArray",
    "PackedVector4Array": "PackedVector4Array",
    "Variant": "any",
    "void": "void",
    "": "void",
}

# Type mapping: Godot type -> C++ QuickJS conversion
GODOT_TO_CPP_FROM_JS = {
    "bool": "JS_ToBool(ctx, {val})",
    "int": "js_to_int(ctx, {val})",
    "float": "js_to_float(ctx, {val})",
    "String": "js_to_string(ctx, {val})",
    "StringName": "StringName(js_to_string(ctx, {val}))",
    "NodePath": "NodePath(js_to_string(ctx, {val}))",
}

GODOT_TO_CPP_TO_JS = {
    "bool": "JS_NewBool(ctx, {val})",
    "int": "JS_NewInt64(ctx, {val})",
    "float": "JS_NewFloat64(ctx, {val})",
    "String": "string_to_js(ctx, {val})",
    "StringName": "string_to_js(ctx, String({val}))",
    "NodePath": "string_to_js(ctx, String({val}))",
    "void": "JS_UNDEFINED",
}


def load_api(api_path):
    with open(api_path) as f:
        return json.load(f)


def load_whitelist(config_path):
    with open(config_path) as f:
        return json.load(f)["classes"]


def godot_type_to_ts(godot_type):
    """Convert a Godot type name to TypeScript type."""
    if not godot_type:
        return "void"
    # Handle enum types like "Node3D.RotationEditMode"
    if "." in godot_type:
        return "number"
    # Handle typed arrays
    if godot_type.startswith("typedarray::"):
        inner = godot_type.replace("typedarray::", "")
        ts_inner = godot_type_to_ts(inner)
        return f"{ts_inner}[]"
    # Handle bitfield
    if godot_type.startswith("bitfield::"):
        return "number"
    # Handle enum
    if godot_type.startswith("enum::"):
        return "number"
    return GODOT_TO_TS.get(godot_type, godot_type)


def is_primitive_type(godot_type):
    """Check if a type is a primitive that we can easily convert."""
    return godot_type in GODOT_TO_CPP_FROM_JS


def generate_ts_declarations(api, whitelist, output_path):
    """Generate TypeScript declaration file."""
    classes = {c["name"]: c for c in api["classes"]}
    lines = []

    lines.append("// Auto-generated by LLM3dEngine binding generator")
    lines.append("// Do not edit manually")
    lines.append("")
    lines.append("declare namespace Engine {")
    lines.append("")

    # Generate builtin type interfaces
    builtin_types = [
        ("Vector2", ["x: number", "y: number"]),
        ("Vector2i", ["x: number", "y: number"]),
        ("Vector3", ["x: number", "y: number", "z: number"]),
        ("Vector3i", ["x: number", "y: number", "z: number"]),
        ("Vector4", ["x: number", "y: number", "z: number", "w: number"]),
        ("Quaternion", ["x: number", "y: number", "z: number", "w: number"]),
        ("Color", ["r: number", "g: number", "b: number", "a: number"]),
        ("Rect2", ["position: Vector2", "size: Vector2"]),
        ("Rect2i", ["position: Vector2i", "size: Vector2i"]),
        ("AABB", ["position: Vector3", "size: Vector3"]),
        ("Plane", ["normal: Vector3", "d: number"]),
        ("Basis", ["x: Vector3", "y: Vector3", "z: Vector3"]),
        ("Transform2D", ["x: Vector2", "y: Vector2", "origin: Vector2"]),
        ("Transform3D", ["basis: Basis", "origin: Vector3"]),
        ("Projection", [
            "x: Vector4", "y: Vector4", "z: Vector4", "w: Vector4"
        ]),
    ]

    for type_name, fields in builtin_types:
        lines.append(f"    interface {type_name} {{")
        for field in fields:
            lines.append(f"        {field};")
        lines.append("    }")
        lines.append("")

    # Utility types
    lines.append("    type RID = number;")
    lines.append("    type Callable = (...args: any[]) => any;")
    lines.append("    type Signal = { connect(callable: Callable): void; disconnect(callable: Callable): void; emit(...args: any[]): void; };")
    lines.append("    type GodotArray = any[];")
    lines.append("    type GodotDictionary = Record<string, any>;")
    lines.append("    type PackedByteArray = Uint8Array;")
    lines.append("    type PackedInt32Array = Int32Array;")
    lines.append("    type PackedInt64Array = BigInt64Array;")
    lines.append("    type PackedFloat32Array = Float32Array;")
    lines.append("    type PackedFloat64Array = Float64Array;")
    lines.append("    type PackedStringArray = string[];")
    lines.append("    type PackedVector2Array = Vector2[];")
    lines.append("    type PackedVector3Array = Vector3[];")
    lines.append("    type PackedColorArray = Color[];")
    lines.append("    type PackedVector4Array = Vector4[];")
    lines.append("")

    # Generate class declarations
    for class_name in whitelist:
        if class_name not in classes:
            lines.append(f"    // WARNING: {class_name} not found in API")
            continue

        cls = classes[class_name]
        inherits = cls.get("inherits", "")
        extends = f" extends {inherits}" if inherits and inherits in whitelist else ""

        lines.append(f"    interface {class_name}{extends} {{")

        # Properties
        for prop in cls.get("properties", []):
            prop_name = prop["name"]
            prop_type = godot_type_to_ts(prop.get("type", "Variant"))
            # Skip properties with / in name (grouped properties)
            if "/" in prop_name:
                continue
            lines.append(f"        {prop_name}: {prop_type};")

        # Methods
        for method in cls.get("methods", []):
            method_name = method["name"]
            # Skip virtual methods (start with _)
            if method_name.startswith("_"):
                continue
            # Skip vararg methods
            if method.get("is_vararg", False):
                continue

            # Build parameter list
            params = []
            for arg in method.get("arguments", []):
                arg_name = arg["name"]
                arg_type = godot_type_to_ts(arg.get("type", "Variant"))
                has_default = "default_value" in arg
                optional = "?" if has_default else ""
                params.append(f"{arg_name}{optional}: {arg_type}")

            # Return type
            ret = method.get("return_value", {})
            ret_type = godot_type_to_ts(ret.get("type", "void"))

            params_str = ", ".join(params)
            lines.append(f"        {method_name}({params_str}): {ret_type};")

        # Signals
        for signal in cls.get("signals", []):
            signal_name = signal["name"]
            lines.append(f"        {signal_name}: Signal;")

        lines.append("    }")
        lines.append("")

    lines.append("}")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path} ({len(lines)} lines)")


def generate_cpp_binding_header(api, whitelist, output_path):
    """Generate C++ binding header."""
    lines = []
    lines.append("// Auto-generated by LLM3dEngine binding generator")
    lines.append("// Do not edit manually")
    lines.append("")
    lines.append("#ifndef QUICKJS_BINDING_GEN_H")
    lines.append("#define QUICKJS_BINDING_GEN_H")
    lines.append("")
    lines.append('extern "C" {')
    lines.append('#include "quickjs.h"')
    lines.append("}")
    lines.append("")
    lines.append("void quickjs_register_generated_bindings(JSContext *ctx, JSValue global);")
    lines.append("")
    lines.append("#endif // QUICKJS_BINDING_GEN_H")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path}")


def generate_cpp_binding(api, whitelist, output_path):
    """Generate C++ QuickJS binding implementation."""
    classes = {c["name"]: c for c in api["classes"]}
    lines = []

    lines.append("// Auto-generated by LLM3dEngine binding generator")
    lines.append("// Do not edit manually")
    lines.append("")
    lines.append('#include "quickjs_binding_gen.h"')
    lines.append("")
    lines.append('#include "core/object/class_db.h"')
    lines.append('#include "core/variant/variant.h"')
    lines.append('#include "scene/main/node.h"')
    lines.append('#include "scene/main/scene_tree.h"')
    lines.append("")
    lines.append("// Helper: convert JS string to Godot String")
    lines.append("static String js_to_string(JSContext *ctx, JSValueConst val) {")
    lines.append("    const char *str = JS_ToCString(ctx, val);")
    lines.append("    String result = str ? String::utf8(str) : String();")
    lines.append("    JS_FreeCString(ctx, str);")
    lines.append("    return result;")
    lines.append("}")
    lines.append("")
    lines.append("// Helper: convert Godot String to JS string")
    lines.append("static JSValue string_to_js(JSContext *ctx, const String &str) {")
    lines.append("    CharString utf8 = str.utf8();")
    lines.append("    return JS_NewStringLen(ctx, utf8.get_data(), utf8.length());")
    lines.append("}")
    lines.append("")
    lines.append("// Helper: convert JS value to int")
    lines.append("static int64_t js_to_int(JSContext *ctx, JSValueConst val) {")
    lines.append("    int64_t result = 0;")
    lines.append("    JS_ToInt64(ctx, &result, val);")
    lines.append("    return result;")
    lines.append("}")
    lines.append("")
    lines.append("// Helper: convert JS value to float")
    lines.append("static double js_to_float(JSContext *ctx, JSValueConst val) {")
    lines.append("    double result = 0;")
    lines.append("    JS_ToFloat64(ctx, &result, val);")
    lines.append("    return result;")
    lines.append("}")
    lines.append("")

    # For each whitelisted class, generate a factory function
    # that creates an instance and returns a JS object with bound methods
    for class_name in whitelist:
        if class_name not in classes:
            continue

        cls = classes[class_name]

        # Generate simple method bindings for methods with primitive types only
        bound_methods = []
        for method in cls.get("methods", []):
            method_name = method["name"]
            if method_name.startswith("_"):
                continue
            if method.get("is_vararg", False):
                continue
            if method.get("is_static", False):
                continue

            # Check if all argument types are primitive
            args = method.get("arguments", [])
            all_primitive = all(is_primitive_type(a.get("type", "")) for a in args)
            ret = method.get("return_value", {})
            ret_type = ret.get("type", "void")
            ret_primitive = ret_type in GODOT_TO_CPP_TO_JS

            if not all_primitive or not ret_primitive:
                continue

            bound_methods.append(method)

            # Generate the C function
            func_name = f"js_{class_name}_{method_name}"
            lines.append(f"static JSValue {func_name}(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {{")
            lines.append(f"    Object *obj = static_cast<Object *>(JS_GetOpaque(this_val, 1));")
            lines.append(f"    if (!obj) return JS_EXCEPTION;")
            lines.append("")

            # Convert arguments
            for i, arg in enumerate(args):
                arg_type = arg.get("type", "")
                conversion = GODOT_TO_CPP_FROM_JS[arg_type].format(val=f"argv[{i}]")
                cpp_type = "bool" if arg_type == "bool" else "int64_t" if arg_type == "int" else "double" if arg_type == "float" else "String"
                lines.append(f"    {cpp_type} arg{i} = {conversion};")

            # Call method via Variant call
            arg_names = ", ".join(f"arg{i}" for i in range(len(args)))
            if ret_type == "void" or ret_type == "":
                lines.append(f'    Callable::CallError ce;')
                if args:
                    lines.append(f'    Variant args[] = {{ {", ".join(f"Variant(arg{i})" for i in range(len(args)))} }};')
                    lines.append(f'    const Variant *argptrs[] = {{ {", ".join(f"&args[{i}]" for i in range(len(args)))} }};')
                    lines.append(f'    obj->callp("{method_name}", argptrs, {len(args)}, ce);')
                else:
                    lines.append(f'    obj->callp("{method_name}", nullptr, 0, ce);')
                lines.append(f"    return JS_UNDEFINED;")
            else:
                lines.append(f'    Callable::CallError ce;')
                if args:
                    lines.append(f'    Variant args[] = {{ {", ".join(f"Variant(arg{i})" for i in range(len(args)))} }};')
                    lines.append(f'    const Variant *argptrs[] = {{ {", ".join(f"&args[{i}]" for i in range(len(args)))} }};')
                    lines.append(f'    Variant ret = obj->callp("{method_name}", argptrs, {len(args)}, ce);')
                else:
                    lines.append(f'    Variant ret = obj->callp("{method_name}", nullptr, 0, ce);')
                to_js = GODOT_TO_CPP_TO_JS[ret_type].format(val=f"({('bool' if ret_type == 'bool' else 'int64_t' if ret_type == 'int' else 'double' if ret_type == 'float' else 'String')})ret")
                lines.append(f"    return {to_js};")

            lines.append("}")
            lines.append("")

        # Generate class prototype setup
        lines.append(f"static void quickjs_register_{class_name}(JSContext *ctx, JSValue global) {{")
        lines.append(f'    JSValue proto = JS_NewObject(ctx);')
        for method in bound_methods:
            method_name = method["name"]
            func_name = f"js_{class_name}_{method_name}"
            argc = len(method.get("arguments", []))
            lines.append(f'    JS_SetPropertyStr(ctx, proto, "{method_name}", JS_NewCFunction(ctx, {func_name}, "{method_name}", {argc}));')
        lines.append(f'    JS_SetPropertyStr(ctx, global, "_{class_name}_proto", proto);')
        lines.append("}")
        lines.append("")

    # Generate main registration function
    lines.append("void quickjs_register_generated_bindings(JSContext *ctx, JSValue global) {")
    for class_name in whitelist:
        if class_name in classes:
            lines.append(f"    quickjs_register_{class_name}(ctx, global);")
    lines.append("}")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path} ({len(lines)} lines)")


def main():
    script_dir = Path(__file__).parent
    project_root = script_dir.parent.parent

    # Paths
    api_path = project_root / "engine" / "godot" / "extension_api.json"
    core_config = script_dir / "config" / "core_api.json"
    ts_output = project_root / "modules" / "quickjs_scripting" / "engine-core.d.ts"
    cpp_header_output = project_root / "modules" / "quickjs_scripting" / "quickjs_binding_gen.h"
    cpp_output = project_root / "modules" / "quickjs_scripting" / "quickjs_binding_gen.cpp"

    if not api_path.exists():
        print(f"ERROR: {api_path} not found.")
        print("Run: ./bin/godot.macos.editor.arm64 --dump-extension-api")
        sys.exit(1)

    print(f"Loading API from {api_path}...")
    api = load_api(api_path)
    print(f"  Found {len(api['classes'])} classes")

    print(f"Loading core API whitelist from {core_config}...")
    whitelist = load_whitelist(core_config)
    print(f"  {len(whitelist)} classes in whitelist")

    print()
    generate_ts_declarations(api, whitelist, ts_output)
    generate_cpp_binding_header(api, whitelist, cpp_header_output)
    generate_cpp_binding(api, whitelist, cpp_output)

    print()
    print("Done!")


if __name__ == "__main__":
    main()
